import java.util.HashMap;
import java.util.Map;

public final class bqh
  implements byp
{
  private static final Map a = new HashMap();
  private static final Map b = new HashMap();
  private static final Map c = new HashMap();
  
  public bqh()
  {
    a.put(bvh.a, "Zgadzam się i chcę zapłacić");
    a.put(bvh.b, "i inne");
    a.put(bvh.c, "Uwierzytelnianie");
    a.put(bvh.d, "Wstecz");
    a.put(bvh.e, "Rezerwowe");
    a.put(bvh.f, "Anuluj");
    a.put(bvh.g, "American Express");
    a.put(bvh.h, "Carta Aura");
    a.put(bvh.i, "Carte Aurore");
    a.put(bvh.j, "Carta Prepagata PayPal");
    a.put(bvh.k, "Carte Bancaire");
    a.put(bvh.l, "Cofinoga");
    a.put(bvh.m, "Delta");
    a.put(bvh.n, "Discover");
    a.put(bvh.o, "Electron");
    a.put(bvh.p, "JCB");
    a.put(bvh.q, "Maestro");
    a.put(bvh.r, "MasterCard");
    a.put(bvh.s, "Postepay");
    a.put(bvh.t, "4 étoiles");
    a.put(bvh.u, "Tarjeta Aurora");
    a.put(bvh.v, "Visa");
    a.put(bvh.w, "Zmień formę płatności");
    a.put(bvh.x, "Rozliczeniowy");
    a.put(bvh.y, "Sprawdzanie urządzenia…");
    a.put(bvh.z, "Wyczyść informacje o karcie");
    a.put(bvh.A, "Potwierdź");
    a.put(bvh.B, "Na pewno chcesz wyczyścić informacje o karcie?");
    a.put(bvh.C, "Obciąż kartę");
    a.put(bvh.D, "Na pewno chcesz się wylogować z serwisu PayPal?");
    a.put(bvh.E, "Zapłać");
    a.put(bvh.F, "Zgadzam się");
    a.put(bvh.G, "Data założenia konta");
    a.put(bvh.H, "Status konta");
    a.put(bvh.I, "Typ rachunku");
    a.put(bvh.J, "Adres");
    a.put(bvh.K, "Grupa wiekowa");
    a.put(bvh.L, "Data urodzenia");
    a.put(bvh.M, "Adres e-mail");
    a.put(bvh.N, "Pełne imię i nazwisko");
    a.put(bvh.O, "Płeć");
    a.put(bvh.P, "Język");
    a.put(bvh.Q, "Lokalizacja");
    a.put(bvh.R, "Telefon");
    a.put(bvh.S, "Strefa czasowa");
    a.put(bvh.T, "Udostępnij następujące informacje: %s.");
    a.put(bvh.U, "Korzystaj z ekspresowej realizacji transakcji.");
    a.put(bvh.V, "%s prosi o:");
    a.put(bvh.W, "Udostępnij <a href='%1$s'>formy płatności</a> powiązane z Twoim kontem PayPal.");
    a.put(bvh.X, "Włącz wyświetlanie opcji finansowania płatności, aby móc dokonać wyboru.");
    a.put(bvh.Y, "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.");
    a.put(bvh.Z, "zgodę na dodawanie kart lojalnościowych i zarządzanie nimi w Twoim portfelu PayPal.");
    a.put(bvh.aa, "akceptację warunków określonych w dokumentach %1$s: <a href='%2$s'>zasadach zachowania poufności</a> i <a href='%3$s'>umowie z użytkownikiem</a>");
    a.put(bvh.ab, "Wyraź zgodę na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    a.put(bvh.ac, "Wyraź zgodę na <a href='%1$s'>wysłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    a.put(bvh.ad, "Zgoda");
    a.put(bvh.ae, "Adres e-mail");
    a.put(bvh.af, "Dane próbne");
    a.put(bvh.ag, "Centrum testowe");
    a.put(bvh.ah, "Wygasa");
    a.put(bvh.ai, "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje formy płatności są dostępne do użytku.</p>");
    a.put(bvh.aj, "Nie pamiętasz hasła?");
    a.put(bvh.ak, "Od");
    a.put(bvh.al, "Jak chcesz finansować przyszłe płatności na rzecz %1$s?");
    a.put(bvh.am, "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Do zapłaty za przyszłe zakupy w systemie PayPal u tego handlowca użyte zostanie Twoje domyślne źródło finansowania płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Obowiązują warunki opisane w rozdziale „Płatności cykliczne” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p><p>Aby mieć pewność, że płatności będą pobierane z Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p>");
    a.put(bvh.an, "Błąd wewnętrzny");
    a.put(bvh.ao, "<p>Klikając przycisk poniżej, akceptuję postanowienia <a href='%1$s'>Umowy z Użytkownikiem usługi PayPal</a> i oświadczam, że przestrzegam przepisów prawa japońskiego, w tym przepisów dotyczących zakazu dokonywania płatności do Korei Północnej i Iranu zgodnie z <a href='%2$s'>ustawą Foreign Exchange and Foreign Trade Act (Ustawa o wymianie walut i handlu zagranicznym)</a> na potrzeby realizacji tej transakcji.</p>");
    a.put(bvh.ap, "Zaloguj się");
    a.put(bvh.aq, "Zaloguj się z PayPal");
    a.put(bvh.ar, "Wyloguj się");
    a.put(bvh.as, "Wyloguj się");
    a.put(bvh.at, "OK");
    a.put(bvh.au, "Hasło");
    a.put(bvh.av, "Zapłać po dostawie");
    a.put(bvh.aw, "Zapłać za pomocą");
    a.put(bvh.ax, "Zapłać kartą");
    a.put(bvh.ay, "Saldo PayPal");
    a.put(bvh.az, "Kredyt PayPal");
    a.put(bvh.aA, "Telefon");
    a.put(bvh.aB, "PIN");
    a.put(bvh.aC, "Preferowana forma płatności");
    a.put(bvh.aD, "Serwis PayPal chroni Twoją <a href='%s'>prywatność</a> i informacje finansowe.");
    a.put(bvh.aE, "Przetwarzanie");
    a.put(bvh.aF, "Zapamiętaj kartę");
    a.put(bvh.aG, "Zażądaj zapłaty");
    a.put(bvh.aH, "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    a.put(bvh.aI, "Oszczędnościowy");
    a.put(bvh.aJ, "Wyślij pieniądze");
    a.put(bvh.aK, "Wystąpił problem z nawiązaniem połączenia z serwerami PayPal. Spróbuj ponownie.");
    a.put(bvh.aL, "Zaloguj się ponownie do systemu PayPal.");
    a.put(bvh.aM, "Sesja wygasła");
    a.put(bvh.aN, "Adres wysyłkowy");
    a.put(bvh.aO, "Nowy użytkownik? Załóż konto");
    a.put(bvh.aP, "Nie wylogowuj się");
    a.put(bvh.aQ, "Błąd systemu (%s). Spróbuj ponownie później.");
    a.put(bvh.aR, "Spróbuj ponownie");
    a.put(bvh.aS, "Logowanie nie powiodło się, ponieważ dla Twojego konta włączono uwierzytelnianie dwuskładnikowe.");
    a.put(bvh.aT, "Kod bezpieczeństwa");
    a.put(bvh.aU, "Wyślij wiadomość tekstową na swój telefon. Otrzymany 6-cyfrowy kod będzie ważny przez 5 minut.");
    a.put(bvh.aV, "Wysyłanie wiadomości tekstowej");
    a.put(bvh.aW, "Podaj 6-cyfrowy kod zabezpieczający");
    a.put(bvh.aX, "Twój numer telefonu komórkowego");
    a.put(bvh.aY, "Wyślij wiadomość tekstową");
    a.put(bvh.aZ, "Wyślij wiadomość tekstową ponownie");
    a.put(bvh.ba, "Logowanie nie powiodło się, ponieważ dla Twojego konta włączono uwierzytelnianie dwuskładnikowe. Przejdź do witryny PayPal i uaktywnij klucz bezpieczeństwa.");
    a.put(bvh.bb, "Dokonywanie płatności z tego urządzenia jest niedozwolone.");
    a.put(bvh.bc, "Nieautoryzowane urządzenie");
    a.put(bvh.bd, "Płatności na rzecz tego handlowca nie są dozwolone (nieprawidłowy identyfikator klienta).");
    a.put(bvh.be, "Nieprawidłowy handlowiec");
    a.put(bvh.bf, "Wystąpił problem z przetworzeniem płatności. Spróbuj ponownie.");
    a.put(bvh.bg, "Nierozpoznane źródło");
    a.put(bvh.bh, "Przepraszamy.");
    a.put(bvh.bi, "Twoje zamówienie");
    a.put(bvh.bj, "Usunąć kartę?");
    a.put(bvh.bk, "Udzielenie zgody nie powiodło się");
    a.put(bvh.bl, "Próba połączenia nieudana");
    a.put(bvh.bm, "Logowanie nie powiodło się");
    a.put(bvh.bn, "Zaloguj się za pomocą hasła");
    a.put(bvh.bo, "Zaloguj się przy użyciu kodu PIN");
    a.put(bvh.bp, "Chwileczkę…");
    a.put(bvh.bq, "Płatność nie powiodła się");
    a.put(bvh.br, "Skanuj");
    a.put(bvh.bs, "Nieprawidłowy kod bezpieczeństwa. Spróbuj ponownie.");
    a.put(bvh.bt, "przez");
    a.put(bvh.bu, "Błąd systemu. Spróbuj ponownie później.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> powiązane z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> powiązane z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.</p><p>Aby uzyskać więcej informacji, zapoznaj się z <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>umową o płatnościach cyklicznych i umową rozliczeniową PayPal</a>.</p>");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.</p><p>Aby uzyskać więcej informacji, zapoznaj się z <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>umową o płatnościach cyklicznych i umową rozliczeniową PayPal</a>.</p>");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Wstępnie zatwierdzaj dokonywane z Twojego konta PayPal płatności z datą przyszłą bez konieczności każdorazowego logowania się w systemie PayPal. <a href='%1$s'>Zobacz dodatkowe warunki</a> dotyczące m.in. form płatności i sposobu anulowania płatności z datą przyszłą.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności (w kolejności: konto PayPal, powiązany rachunek bankowy, karta debetowa lub kredytowa). Pamiętaj, że jeśli w ramach swojej domyślnej formy płatności nie masz wystarczających środków do dokonania płatności za zakupy, Twój bank lub wystawca karty może obciążyć Cię opłatą.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong>, <strong>Moje ustawienia</strong> i opcję <strong>Zmień</strong> dostępną obok pozycji Zaloguj się z PayPal.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Płatności za zakupy w systemie PayPal zostaną pobrane z salda Twojego konta PayPal lub podstawowej karty kredytowej albo debetowej.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Do zapłaty za przyszłe zakupy w systemie PayPal u tego handlowca użyte zostanie Twoje domyślne źródło finansowania płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Obowiązują warunki opisane w rozdziale „Płatności cykliczne” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p><p>Aby mieć pewność, że płatności będą pobierane z Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Płatności za zakupy w systemie PayPal zostaną pobrane z salda Twojego konta PayPal lub podstawowej karty kredytowej albo debetowej.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>W celu realizacji zakupu system PayPal w pierwszej kolejności korzysta ze środków na Twoim koncie PayPal. Jeśli środki te są niewystarczające, wykorzystane zostaną kolejno: rachunek bankowy, PayPal Credit, karta debetowa, karta kredytowa lub czek elektroniczny.</p><p>Aby anulować tę umowę, na stronie www.paypal.pl wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Autoryzacja płatności o mniejszej wartości może być wymagana w celu sprawdzenia, czy konto PayPal może być obciążane. Taka autoryzacja zostanie jednak unieważniona, a pobranie opłaty anulowane.</p>");
    b.put("LOG_IN_TO_PAYPAL|AU", "Zaloguj się z PayPal");
    b.put("LOG_IN_TO_PAYPAL|GB", "Zaloguj się z PayPal");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Centrum bezpieczeństwa</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca. Jeśli korzystasz z klasycznej strony internetowej, wybierz kolejno <strong>Mój profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.it, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.ru, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.com.tr, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
    c.put("AMOUNT_MISMATCH", "Suma wszystkich pozycji w koszyku jest niezgodna z kwotą sprzedaży.");
    c.put("AUTHORIZATION_ALREADY_COMPLETED", "Ta autoryzacja została już zakończona.");
    c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autoryzacji w aktualnym stanie nie można unieważnić.");
    c.put("AUTHORIZATION_EXPIRED", "Autoryzacja straciła ważność.");
    c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Numer identyfikacyjny żądanej autoryzacji nie istnieje.");
    c.put("AUTHORIZATION_VOIDED", "Autoryzacja została anulowana.");
    c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Ponownej autoryzacji można dokonać tylko w ramach pierwotnej autoryzacji.");
    c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ponowna autoryzacja nie jest dozwolona w okresie honorowania.");
    c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Kwota przekracza dopuszczalny limit.");
    c.put("CARD_TOKEN_PAYER_MISMATCH", "Brak dostępu do zapisanych informacji o karcie.");
    c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Dane karty są nieprawidłowe. Popraw je i prześlij ponownie.");
    c.put("CREDIT_CARD_REFUSED", "Karta została odrzucona.");
    c.put("CURRENCY_MISMATCH", "Waluta pobranych środków musi być jednakowa z walutą autoryzacji.");
    c.put("CURRENCY_NOT_ALLOWED", "Twoja waluta nie jest aktualnie obsługiwana przez system PayPal.");
    c.put("DATA_RETRIEVAL", "Błąd systemu. Spróbuj ponownie później.");
    c.put("DUPLICATE_REQUEST_ID", "Błąd systemu. Spróbuj ponownie później.");
    c.put("EXPIRED_CREDIT_CARD", "Karta wygasła");
    c.put("EXPIRED_CREDIT_CARD_TOKEN", "W systemie nie ma już zapisanych informacji o tej karcie.\nPrześlij je ponownie.");
    c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funkcja nie jest obsługiwana u tego handlowca.");
    c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Ta transakcja została już częściowo zwrócona.");
    c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Płatność natychmiastowa nie jest obsługiwana w wybranej opcji.");
    c.put("INSTRUMENT_DECLINED", "Wybrana przez Ciebie forma płatności nie została zaakceptowana. Wybierz inną formę płatności.");
    c.put("INSUFFICIENT_FUNDS", "Kupujący nie może zapłacić – niewystarczające środki.");
    c.put("INTERNAL_SERVICE_ERROR", "Błąd systemu. Spróbuj ponownie później.");
    c.put("INVALID_ACCOUNT_NUMBER", "Ten numer rachunku nie istnieje.");
    c.put("INVALID_ARGUMENT", "Transakcja odrzucona z powodu nieprawidłowego parametru");
    c.put("INVALID_CITY_STATE_ZIP", "Nieprawidłowa kombinacja miasta/województwa/kodu pocztowego.");
    c.put("INVALID_FACILITATOR_CONFIGURATION", "Nie można przetworzyć transakcji. Podana konfiguracja facylitatora jest nieprawidłowa.");
    c.put("INVALID_PAYER_ID", "Błąd systemu (nieprawidłowy identyfikator płatnika). Spróbuj ponownie później.");
    c.put("INVALID_RESOURCE_ID", "Błąd systemu. Spróbuj ponownie później.");
    c.put("PAYEE_ACCOUNT_INVALID", "Handlowiec nie posiada potwierdzonego adresu e-mail.");
    c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Ten dostawca nie może obecnie odbierać płatności.");
    c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Handlowiec nie posiada potwierdzonego adresu e-mail.");
    c.put("PAYEE_ACCOUNT_RESTRICTED", "Ten dostawca nie może obecnie odbierać płatności.");
    c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Twoje konto zostało zablokowane lub zamknięte.");
    c.put("PAYER_ACCOUNT_RESTRICTED", "Dostęp do Twojego konta został ograniczony.");
    c.put("PAYER_CANNOT_PAY", "Nie możesz zapłacić za tę transakcję z PayPal.");
    c.put("PAYER_EMPTY_BILLING_ADDRESS", "W przypadku transakcji kartą kredytową poza systemem PayPal wymagany jest adres rozliczeniowy.");
    c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Brak dostępu do zapisanych informacji o karcie.");
    c.put("PAYMENT_APPROVAL_EXPIRED", "Zatwierdzenie płatności straciło ważność.");
    c.put("PAYMENT_EXPIRED", "Płatność straciła ważność.");
    c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Płatnik nie zatwierdził płatności.");
    c.put("PAYMENT_REQUEST_ID_INVALID", "Identyfikator żądania PayPal jest nieprawidłowy. Spróbuj ponownie później.");
    c.put("PAYMENT_STATE_INVALID", "Żądanie jest nieprawidłowe z uwagi na aktualny status płatności.");
    c.put("PERMISSION_DENIED", "Brak uprawnień do wykonania żądanej operacji.");
    c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Żądana kwota zwrotu pieniędzy przekracza kwotę pierwotnej transakcji.");
    c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transakcja została dokonana zbyt dawno, aby dokonać zwrotu pieniędzy.");
    c.put("REQUIRED_SCOPE_MISSING", "Błąd systemu. Spróbuj ponownie później.");
    c.put("TOO_MANY_REAUTHORIZATIONS", "Nie można dokonać więcej ponownych autoryzacji w ramach tej autoryzacji.");
    c.put("TRANSACTION_ALREADY_REFUNDED", "Ta transakcja została już zwrócona.");
    c.put("TRANSACTION_LIMIT_EXCEEDED", "Kwota przekracza dopuszczalny limit.");
    c.put("TRANSACTION_REFUSED", "Transakcja została odrzucona.");
    c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transakcja została odrzucona.");
    c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Preferencje w profilu handlowca ustawione są na automatyczne odrzucanie pewnych transakcji.");
    c.put("UNKNOWN_ERROR", "Błąd systemu. Spróbuj ponownie później.");
    c.put("UNSUPPORTED_PAYEE_COUNTRY", "Twój kraj nie jest obsługiwany.");
    c.put("VALIDATION_ERROR", "Informacje o płatności są nieprawidłowe. Popraw je i prześlij ponownie.");
    c.put("ORDER_ALREADY_COMPLETED", "Zamówienie zostało już unieważnione, straciło ważność lub zostało zrealizowane.");
    c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Osiągnięto limit dozwolonych autoryzacji w ramach tego zamówienia.");
    c.put("ORDER_VOIDED", "Zamówienie zostało unieważnione.");
    c.put("ORDER_CANNOT_BE_VOIDED", "Obecny status zamówienia uniemożliwia jego unieważnienie.");
    c.put("INVALID_EXPERIENCE_PROFILE_ID", "Błąd systemu. Spróbuj ponownie później.");
    c.put("UNAUTHORIZED_PAYMENT", "Handlowiec nie akceptuje płatności tego typu.");
    c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Waluta nie jest obsługiwana przez ten typ karty.");
    c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Ten typ karty nie jest obsługiwany.");
    c.put("ADDRESS_ADDITION_ERROR", "Podczas dodawania adresu wysyłkowego do konta PayPal wystąpił błąd.");
    c.put("DUPLICATE_TRANSACTION", "Transakcja powielona.");
    c.put("INVALID_SHIPPING_ADDRESS", "Podany adres wysyłkowy jest nieprawidłowy.");
    c.put("PAYMENT_CREATION_ERROR", "Wystąpił problem z utworzeniem tej płatności. Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Wystąpił problem z utworzeniem tej płatności – Twoja karta wygasła. Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Wystąpił problem z utworzeniem tej płatności – wymagana jest płatność błyskawiczna (na przykład kartą kredytową). Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Wystąpił problem z utworzeniem tej płatności – karta musi zostać potwierdzona. Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Wystąpił problem z utworzeniem tej płatności – ta aplikacja wymaga, aby na Twoim koncie podany został numer telefonu. Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Wystąpił problem z utworzeniem tej płatności – konto wymaga podania ważnego źródła finansowania płatności, np. rachunku bankowego lub karty płatniczej. Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Wystąpił problem z utworzeniem tej płatności – saldo konta jest ujemne. Sprawdź swoje konto w witrynie PayPal.");
    c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Wystąpił problem z utworzeniem tej płatności – osiągnięto limit wysyłania. Sprawdź swoje konto w witrynie PayPal.");
    c.put("AUTH_RC_RISK_FAILURE", "Odrzucono z uwagi na ryzyko.");
    c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klient nieautoryzowany.");
    c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klient nieautoryzowany.");
    c.put("invalid_user", "Nieprawidłowa nazwa użytkownika / hasło. Spróbuj ponownie.");
    c.put("locked_user", "Twoje konto PayPal zostało tymczasowo zablokowane. Spróbuj ponownie później lub przejdź do witryny www.paypal.pl i odblokuj swoje konto PayPal.");
    c.put("max_attempts_exceeded", "Zbyt wiele prób logowania zakończyło się niepowodzeniem. Spróbuj ponownie później.");
    c.put("invalid_request", "Wystąpił błąd.");
    c.put("unauthorized_client", "Żądanie nieautoryzowane.");
    c.put("access_denied", "Żądanie nieautoryzowane.");
    c.put("unsupported_response_type", "Wystąpił błąd.");
    c.put("invalid_scope", "Żądanie nieautoryzowane.");
    c.put("server_error", "Błąd systemu. Spróbuj ponownie później.");
    c.put("temporarily_unavailable", "Błąd systemu. Spróbuj ponownie później.");
    c.put("stepup_required", "W tej chwili nie możesz się zalogować. Spróbuj ponownie później lub przejdź do witryny www.paypal.pl i odpowiedz na wątpliwości dotyczące bezpieczeństwa Twojego konta PayPal.");
  }
  
  public final String a()
  {
    return "pl";
  }
  
  public final String a(String paramString)
  {
    return (String)c.get(paramString);
  }
}

/* Location:
 * Qualified Name:     bqh
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */