import java.util.HashMap;
import java.util.Map;

public final class cff
  implements byp
{
  private static final Map a = new HashMap();
  private static final Map b = new HashMap();
  private static final Map c = new HashMap();
  
  public cff()
  {
    a.put(bvh.a, "Accetta e paga");
    a.put(bvh.b, "e altri");
    a.put(bvh.c, "Autenticazione…");
    a.put(bvh.d, "Prec.");
    a.put(bvh.e, "Di riserva");
    a.put(bvh.f, "Annulla");
    a.put(bvh.g, "American Express");
    a.put(bvh.h, "Carta Aura");
    a.put(bvh.i, "Carta Aurore");
    a.put(bvh.j, "Carta Prepagata PayPal");
    a.put(bvh.k, "Carte Bancaire");
    a.put(bvh.l, "Cofinoga");
    a.put(bvh.m, "Delta");
    a.put(bvh.n, "Discover");
    a.put(bvh.o, "Electron");
    a.put(bvh.p, "JCB");
    a.put(bvh.q, "Maestro");
    a.put(bvh.r, "MasterCard");
    a.put(bvh.s, "Postepay");
    a.put(bvh.t, "4 étoiles");
    a.put(bvh.u, "Tarjeta Aurora");
    a.put(bvh.v, "Visa");
    a.put(bvh.w, "Modifica metodo di pagamento");
    a.put(bvh.x, "Conto corrente");
    a.put(bvh.y, "Controllo dispositivo…");
    a.put(bvh.z, "Rimuovi dati della carta");
    a.put(bvh.A, "Conferma");
    a.put(bvh.B, "Rimuovere i dati della carta?");
    a.put(bvh.C, "Addebita importo sulla carta");
    a.put(bvh.D, "Vuoi uscire da PayPal?");
    a.put(bvh.E, "Paga");
    a.put(bvh.F, "Accetta");
    a.put(bvh.G, "Data creazione conto");
    a.put(bvh.H, "Stato del conto");
    a.put(bvh.I, "Tipo di conto");
    a.put(bvh.J, "Indirizzo");
    a.put(bvh.K, "Fascia di età");
    a.put(bvh.L, "Data di nascita");
    a.put(bvh.M, "Indirizzo email");
    a.put(bvh.N, "Nome e cognome");
    a.put(bvh.O, "Sesso");
    a.put(bvh.P, "Lingua");
    a.put(bvh.Q, "Locale");
    a.put(bvh.R, "Telefono");
    a.put(bvh.S, "Fuso orario");
    a.put(bvh.T, "Condividi il seguente: %s.");
    a.put(bvh.U, "Usa Pagamento express.");
    a.put(bvh.V, "%s ti chiede di:");
    a.put(bvh.W, "Condividi i <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    a.put(bvh.X, "Per effettuare una scelta, attiva la visualizzazione dei metodi di pagamento.");
    a.put(bvh.Y, "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.");
    a.put(bvh.Z, "consentirgli di aggiungere e gestire la propria carta fedeltà nel tuo portafoglio PayPal.");
    a.put(bvh.aa, "Accettare l’<a href='%2$s'></a> Informativa sulla privacy<a href='%3$s'> e le</a> Condizioni d’uso di %1$s.");
    a.put(bvh.ab, "Consentirgli di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    a.put(bvh.ac, "Consentirgli di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    a.put(bvh.ad, "Consenso");
    a.put(bvh.ae, "Email");
    a.put(bvh.af, "Dati di esempio");
    a.put(bvh.ag, "Sandbox");
    a.put(bvh.ah, "Scadenza");
    a.put(bvh.ai, "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal condivide solo i tuoi metodi di pagamento disponibili per l’utilizzo.</p>");
    a.put(bvh.aj, "Password dimenticata?");
    a.put(bvh.ak, "Da");
    a.put(bvh.al, "Come vuoi pagare i prossimi acquisti su %1$s?");
    a.put(bvh.am, "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>Si applica la sezione Pagamenti automatici delle <a href='%s'>Condizioni d’uso PayPal</a>.</p><p>Per verificare il funzionamento dell’addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
    a.put(bvh.an, "Errore interno");
    a.put(bvh.ao, "<p>Cliccando il pulsante di seguito, accetto le <a href='%1$s'>Condizioni d’uso PayPal</a> e dichiaro di rispettare le leggi e normative del Giappone, tra cui le sanzioni previste per i pagamenti alla Corea del Nord e all’Iran in base al <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> (Legge sugli scambi e sul commercio estero), per completare la transazione.</p>");
    a.put(bvh.ap, "Accedi");
    a.put(bvh.aq, "Log in con PayPal");
    a.put(bvh.ar, "Esci");
    a.put(bvh.as, "Esci");
    a.put(bvh.at, "OK");
    a.put(bvh.au, "Password");
    a.put(bvh.av, "Paga dopo la consegna");
    a.put(bvh.aw, "Paga con");
    a.put(bvh.ax, "Paga con una carta");
    a.put(bvh.ay, "Saldo PayPal");
    a.put(bvh.az, "PayPal Credit");
    a.put(bvh.aA, "Telefono");
    a.put(bvh.aB, "PIN");
    a.put(bvh.aC, "Metodo di pagamento preferito");
    a.put(bvh.aD, "PayPal protegge la tua <a href='%s'>privacy</a> e i tuoi dati.");
    a.put(bvh.aE, "Elaborazione in corso");
    a.put(bvh.aF, "Ricorda dati carta");
    a.put(bvh.aG, "Richiedi denaro");
    a.put(bvh.aH, "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    a.put(bvh.aI, "Conto corrente");
    a.put(bvh.aJ, "Invia denaro");
    a.put(bvh.aK, "Si è verificato un problema con i nostri server. Riprova.");
    a.put(bvh.aL, "Ripeti l’accesso a PayPal.");
    a.put(bvh.aM, "Sessione scaduta");
    a.put(bvh.aN, "Indirizzo di spedizione");
    a.put(bvh.aO, "Non hai un conto PayPal? Registrati");
    a.put(bvh.aP, "Rimani collegato");
    a.put(bvh.aQ, "Errore di sistema (%s). Riprova più tardi.");
    a.put(bvh.aR, "Riprova");
    a.put(bvh.aS, "Impossibile effettuare l’accesso perché sul tuo conto è attiva la doppia autenticazione.");
    a.put(bvh.aT, "Codice di sicurezza");
    a.put(bvh.aU, "Ricevi un SMS sul tuo telefono. Il codice a 6 cifre sarà valido per 5 minuti.");
    a.put(bvh.aV, "Invio SMS in corso");
    a.put(bvh.aW, "Immetti il codice di sicurezza a 6 cifre");
    a.put(bvh.aX, "Numero di cellulare");
    a.put(bvh.aY, "Ricevi SMS");
    a.put(bvh.aZ, "Ricevi un altro SMS");
    a.put(bvh.ba, "Impossibile effettuare l’accesso perché sul tuo conto è attiva la doppia autenticazione. Visita il sito PayPal per attivare la chiave di accesso.");
    a.put(bvh.bb, "Pagamenti da questo dispositivo non consentiti.");
    a.put(bvh.bc, "Dispositivo non autorizzato");
    a.put(bvh.bd, "I pagamenti a questo venditore non sono consentiti (clientId non valido).");
    a.put(bvh.be, "Sito non valido");
    a.put(bvh.bf, "Si è verificato un problema durante l’elaborazione del pagamento. Riprova.");
    a.put(bvh.bg, "Metodo non riconosciuto");
    a.put(bvh.bh, "Spiacenti");
    a.put(bvh.bi, "Il tuo ordine");
    a.put(bvh.bj, "Rimuovere la carta?");
    a.put(bvh.bk, "Consenso non riuscito");
    a.put(bvh.bl, "Connessione non riuscita");
    a.put(bvh.bm, "Accesso non riuscito");
    a.put(bvh.bn, "Accedi con la password");
    a.put(bvh.bo, "Accedi con il PIN");
    a.put(bvh.bp, "Attendi…");
    a.put(bvh.bq, "Pagamento non riuscito");
    a.put(bvh.br, "Scansione");
    a.put(bvh.bs, "Codice di sicurezza errato. Riprova.");
    a.put(bvh.bt, "tramite");
    a.put(bvh.bu, "Errore di sistema. Riprova più tardi.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Condividi con loro i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preautorizza i prossimi pagamenti dal tuo conto PayPal senza effettuare ogni volta l’accesso al conto. <a href='%1$s'>Vedi le condizioni aggiuntive</a>, tra cui i metodi di pagamento e le modalità di annullamento dei pagamenti preautorizzati.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito (il saldo PayPal, il conto bancario, la carta di credito o di debito, in quest’ordine) verrà usato per pagare gli acquisti con PayPal. Se sul tuo metodo di pagamento preferito non è presente denaro sufficiente per l’acquisto, la banca o la società emittente della carta potrebbe addebitarti una tariffa.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Modifica</strong> accanto a “Log in con PayPal”.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verrà usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Si applica la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p><p>Per verificare il funzionamento dell’addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a> per maggiori informazioni.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verrà usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Come prima opzione per pagare i tuoi acquisti, verrà usato il tuo saldo PayPal. Se non è sufficiente, verranno usati, nell’ordine, il conto bancario, PayPal Credit, la carta di debito (bancomat), la carta di credito e/o gli eCheck.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante dall’elenco.</p><p>Potrebbe essere richiesta l’autorizzazione di un piccolo pagamento per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal. L’autorizzazione verrà annullata e non ti verrà addebitato alcun importo.</p>");
    b.put("LOG_IN_TO_PAYPAL|AU", "Log in con PayPal");
    b.put("LOG_IN_TO_PAYPAL|GB", "Log in con PayPal");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco. Se usi ancora la versione classica del sito, vai al tuo <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
    c.put("AMOUNT_MISMATCH", "Il totale del carrello non corrisponde all’importo delle vendite.");
    c.put("AUTHORIZATION_ALREADY_COMPLETED", "L’autorizzazione è già stata completata.");
    c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "L’autorizzazione è in una provincia in cui non può essere annullata.");
    c.put("AUTHORIZATION_EXPIRED", "L’autorizzazione è scaduta.");
    c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "L’ID autorizzazione richiesto non esiste.");
    c.put("AUTHORIZATION_VOIDED", "L’autorizzazione è stata annullata.");
    c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "È possibile riautorizzare solo le autorizzazioni originali.");
    c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "La riautorizzazione non è consentita nel periodo di validità.");
    c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "L’importo supera il limite consentito.");
    c.put("CARD_TOKEN_PAYER_MISMATCH", "Impossibile accedere ai dati della carta in archivio.");
    c.put("CREDIT_CARD_CVV_CHECK_FAILED", "I dati della carta non sono validi. Correggi i tuoi dati e riprova.");
    c.put("CREDIT_CARD_REFUSED", "Carta rifiutata.");
    c.put("CURRENCY_MISMATCH", "La valuta di riscossione deve essere uguale a quella di autorizzazione.");
    c.put("CURRENCY_NOT_ALLOWED", "Valuta non supportata da PayPal.");
    c.put("DATA_RETRIEVAL", "Errore di sistema. Riprova più tardi.");
    c.put("DUPLICATE_REQUEST_ID", "Errore di sistema. Riprova più tardi.");
    c.put("EXPIRED_CREDIT_CARD", "La carta è scaduta");
    c.put("EXPIRED_CREDIT_CARD_TOKEN", "I dati di questa carta non sono più in archivio.\nInoltrali di nuovo.");
    c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "La funzione non è supportata per questo beneficiario.");
    c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "La transazione è stata già rimborsata parzialmente.");
    c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "L’opzione di pagamento immediato non è supportata per la finalità impostata.");
    c.put("INSTRUMENT_DECLINED", "Il metodo di pagamento selezionato non è stato accettato. Scegli un altro metodo di pagamento.");
    c.put("INSUFFICIENT_FUNDS", "L’acquirente non può pagare per denaro insufficiente.");
    c.put("INTERNAL_SERVICE_ERROR", "Errore di sistema. Riprova più tardi.");
    c.put("INVALID_ACCOUNT_NUMBER", "Il numero di conto non esiste.");
    c.put("INVALID_ARGUMENT", "Transazione rifiutata per problemi tecnici");
    c.put("INVALID_CITY_STATE_ZIP", "Combinazione Città/Provincia/CAP non valida.");
    c.put("INVALID_FACILITATOR_CONFIGURATION", "Impossibile elaborare la transazione per configurazione non valida.");
    c.put("INVALID_PAYER_ID", "Errore di sistema (ID acquirente non valido). Riprova più tardi.");
    c.put("INVALID_RESOURCE_ID", "Errore di sistema. Riprova più tardi.");
    c.put("PAYEE_ACCOUNT_INVALID", "Il conto del beneficiario non ha un’email confermata.");
    c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Questo venditore non può ricevere pagamenti al momento.");
    c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Il conto del beneficiario non ha un’email confermata.");
    c.put("PAYEE_ACCOUNT_RESTRICTED", "Questo venditore non può ricevere pagamenti al momento.");
    c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Il tuo conto è bloccato o chiuso.");
    c.put("PAYER_ACCOUNT_RESTRICTED", "Il tuo conto è stato limitato.");
    c.put("PAYER_CANNOT_PAY", "Impossibile inviare questo pagamento con PayPal.");
    c.put("PAYER_EMPTY_BILLING_ADDRESS", "L’indirizzo di fatturazione è obbligatorio per le transazioni con carta non effettuate con PayPal.");
    c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Impossibile accedere ai dati della carta in archivio.");
    c.put("PAYMENT_APPROVAL_EXPIRED", "L’approvazione del pagamento è scaduta.");
    c.put("PAYMENT_EXPIRED", "Il pagamento è scaduto.");
    c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "L’acquirente non ha approvato il pagamento.");
    c.put("PAYMENT_REQUEST_ID_INVALID", "Il codice (ID) di richiesta PayPal non è valido. Riprova più tardi.");
    c.put("PAYMENT_STATE_INVALID", "Richiesta non valida nella provincia di pagamento.");
    c.put("PERMISSION_DENIED", "L’operazione richiesta non è autorizzata.");
    c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Il rimborso richiesto supera l’importo della transazione originale.");
    c.put("REFUND_TIME_LIMIT_EXCEEDED", "Questa transazione è troppo datata per essere rimborsata.");
    c.put("REQUIRED_SCOPE_MISSING", "Errore di sistema. Riprova più tardi.");
    c.put("TOO_MANY_REAUTHORIZATIONS", "Per questa autorizzazione non sono più consentite riautorizzazioni.");
    c.put("TRANSACTION_ALREADY_REFUNDED", "La transazione è stata già rimborsata.");
    c.put("TRANSACTION_LIMIT_EXCEEDED", "L’importo supera il limite consentito.");
    c.put("TRANSACTION_REFUSED", "La transazione è stata rifiutata.");
    c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "La transazione è stata rifiutata.");
    c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Le preferenze del commerciante sono impostate per rifiutare automaticamente determinate transazioni.");
    c.put("UNKNOWN_ERROR", "Errore di sistema. Riprova più tardi.");
    c.put("UNSUPPORTED_PAYEE_COUNTRY", "Il tuo Paese non è supportato.");
    c.put("VALIDATION_ERROR", "I dati di pagamento non sono validi. Correggi i tuoi dati e riprova.");
    c.put("ORDER_ALREADY_COMPLETED", "L’ordine è stato già annullato, è scaduto o completato.");
    c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Il numero massimo di autorizzazioni consentite per l’ordine è stato raggiunto.");
    c.put("ORDER_VOIDED", "L’ordine è stato annullato.");
    c.put("ORDER_CANNOT_BE_VOIDED", "L’ordine è in uno stato che impedisce l’annullamento.");
    c.put("INVALID_EXPERIENCE_PROFILE_ID", "Errore di sistema. Riprova più tardi.");
    c.put("UNAUTHORIZED_PAYMENT", "Il commerciante non accetta questo tipo di pagamenti.");
    c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta non supportata per il tipo di carta.");
    c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo di carta non supportato.");
    c.put("ADDRESS_ADDITION_ERROR", "Si è verificato un errore durante l’aggiunta dell’indirizzo di spedizione al conto PayPal.");
    c.put("DUPLICATE_TRANSACTION", "Transazione doppia");
    c.put("INVALID_SHIPPING_ADDRESS", "L’indirizzo di spedizione non è valido.");
    c.put("PAYMENT_CREATION_ERROR", "Si è verificato un problema nella disposizione del pagamento. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Si è verificato un problema nella disposizione del pagamento: la tua carta è scaduta. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Si è verificato un problema nella disposizione del pagamento: è richiesto un pagamento immediato, ad esempio una carta di credito. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Si è verificato un problema nella disposizione del pagamento: la carta deve essere confermata. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Si è verificato un problema nella disposizione del pagamento: questa applicazione richiede che sul tuo conto sia registrato un numero di telefono. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Si è verificato un problema nella disposizione del pagamento: il conto necessita di un metodo di pagamento valido, ad esempio un conto bancario o una carta di pagamento. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Si è verificato un problema nella disposizione del pagamento: il tuo saldo è negativo. Vai su paypal.it e controlla il tuo conto.");
    c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Si è verificato un problema nella disposizione del pagamento: hai raggiunto il tuo limite di invio. Vai su paypal.it e controlla il tuo conto.");
    c.put("AUTH_RC_RISK_FAILURE", "Rifiutata per motivi di rischio.");
    c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client non autorizzato.");
    c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client non autorizzato.");
    c.put("invalid_user", "Email o password non corretta. Riprova.");
    c.put("locked_user", "Il tuo conto PayPal è stato temporaneamente bloccato. Riprova più tardi o accedi a www.paypal.com per sbloccare immediatamente il tuo conto PayPal.");
    c.put("max_attempts_exceeded", "Troppi tentativi di accesso non riusciti. Riprova più tardi.");
    c.put("invalid_request", "Si è verificato un errore.");
    c.put("unauthorized_client", "Richiesta non autorizzata.");
    c.put("access_denied", "Richiesta non autorizzata.");
    c.put("unsupported_response_type", "Si è verificato un errore.");
    c.put("invalid_scope", "Richiesta non autorizzata.");
    c.put("server_error", "Errore di sistema. Riprova più tardi.");
    c.put("temporarily_unavailable", "Errore di sistema. Riprova più tardi.");
    c.put("stepup_required", "Non è possibile completare l’accesso. Riprova più tardi o accedi a www.paypal.it per risolvere eventuali problema di sicurezza del tuo conto PayPal.");
  }
  
  public final String a()
  {
    return "it";
  }
  
  public final String a(String paramString)
  {
    return (String)c.get(paramString);
  }
}

/* Location:
 * Qualified Name:     cff
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */