import java.util.HashMap;
import java.util.Map;

public final class cfy
  implements cav
{
  private static final Map a = new HashMap();
  private static final Map b = new HashMap();
  private static final Map c = new HashMap();
  
  public cfy()
  {
    a.put(bxn.a, "Aceptar y pagar");
    a.put(bxn.b, "y otras");
    a.put(bxn.c, "Autenticando");
    a.put(bxn.d, "Atrás");
    a.put(bxn.e, "Garantía");
    a.put(bxn.f, "Cancelar");
    a.put(bxn.g, "American Express");
    a.put(bxn.h, "Carta Aura");
    a.put(bxn.i, "Tarjeta Aurora");
    a.put(bxn.j, "Carta Prepagata PayPal");
    a.put(bxn.k, "Carte Bancaire");
    a.put(bxn.l, "Cofinoga");
    a.put(bxn.m, "Delta");
    a.put(bxn.n, "Discover");
    a.put(bxn.o, "Electron");
    a.put(bxn.p, "JCB");
    a.put(bxn.q, "Maestro");
    a.put(bxn.r, "MasterCard");
    a.put(bxn.s, "Postepay");
    a.put(bxn.t, "4 étoiles");
    a.put(bxn.u, "Tarjeta Aurora");
    a.put(bxn.v, "Visa");
    a.put(bxn.w, "Cambiar forma de pago");
    a.put(bxn.x, "Corriente");
    a.put(bxn.y, "Comprobando este dispositivo…");
    a.put(bxn.z, "Borrar información de tarjeta");
    a.put(bxn.A, "Confirmar");
    a.put(bxn.B, "¿Seguro de que deseas borrar la información de la tarjeta?");
    a.put(bxn.C, "Cargar en tarjeta");
    a.put(bxn.D, "¿Seguro que deseas cerrar la sesión de PayPal?");
    a.put(bxn.E, "Pagar");
    a.put(bxn.F, "Aceptar");
    a.put(bxn.G, "Fecha de creación de la cuenta");
    a.put(bxn.H, "Estado de cuenta");
    a.put(bxn.I, "Tipo de cuenta");
    a.put(bxn.J, "Dirección");
    a.put(bxn.K, "Intervalo de edad");
    a.put(bxn.L, "Fecha de nacimiento");
    a.put(bxn.M, "Dirección de correo");
    a.put(bxn.N, "Nombre completo");
    a.put(bxn.O, "Sexo");
    a.put(bxn.P, "Idioma");
    a.put(bxn.Q, "Región");
    a.put(bxn.R, "Teléfono");
    a.put(bxn.S, "Zona horaria");
    a.put(bxn.T, "Compartir lo siguiente: %s.");
    a.put(bxn.U, "Utilizar el pago totalmente integrado.");
    a.put(bxn.V, "%s te pide que:");
    a.put(bxn.W, "Compartir las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
    a.put(bxn.X, "Activa la visualización de las opciones de pago para poder elegir.");
    a.put(bxn.Y, "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indica a PayPal que pague todos los importes solicitados por %3$s.");
    a.put(bxn.Z, "Le permitas añadir y administrar su tarjeta de fidelización en tu cartera de PayPal.");
    a.put(bxn.aa, "Aceptes la <a href='%2$s'>política de privacidad</a> y las <a href='%3$s'>condiciones de uso</a> de %1$s.");
    a.put(bxn.ab, "Le permitas <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    a.put(bxn.ac, "Le permitas <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    a.put(bxn.ad, "Consentimiento");
    a.put(bxn.ae, "Correo");
    a.put(bxn.af, "Datos simulados");
    a.put(bxn.ag, "Entorno de pruebas");
    a.put(bxn.ah, "Caduca");
    a.put(bxn.ai, "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su uso.</p>");
    a.put(bxn.aj, "¿Has olvidado la contraseña?");
    a.put(bxn.ak, "De");
    a.put(bxn.al, "¿Cómo te gustaría realizar los pagos futuros a %1$s?");
    a.put(bxn.am, "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Se utilizará la fuente de fondos predeterminada para realizar futuros pagos con PayPal desde este vendedor.</p><p>Para cancelar este acuerdo, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Se aplicará la sección Pagos periódicos de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarte de que los pagos con tu cuenta PayPal funcionen correctamente, esta aplicación puede simular una pequeña transacción de prueba, pero no se transferirá dinero.</p>");
    a.put(bxn.an, "Error interno");
    a.put(bxn.ao, "<p>Al hacer clic en el botón siguiente, por el presente documento acepto las condiciones que figuran en las <a href='%1$s'>Condiciones de uso de PayPal</a> y declaro que cumplo las leyes y normas japonesas, incluidas las sanciones contra pagos a Corea del Norte e Irán que se establecen en la <a href='%2$s'>ley de divisas y comercio exterior</a> para completar la transacción.</p>");
    a.put(bxn.ap, "Iniciar sesión");
    a.put(bxn.aq, "Iniciar sesión con PayPal");
    a.put(bxn.ar, "Cerrar sesión");
    a.put(bxn.as, "Cerrar sesión");
    a.put(bxn.at, "Aceptar");
    a.put(bxn.au, "Contraseña");
    a.put(bxn.av, "Pago tras la entrega");
    a.put(bxn.aw, "Pagar con");
    a.put(bxn.ax, "Pagar con tarjeta");
    a.put(bxn.ay, "Saldo de PayPal");
    a.put(bxn.az, "PayPal Credit");
    a.put(bxn.aA, "Teléfono");
    a.put(bxn.aB, "PIN");
    a.put(bxn.aC, "Forma de pago preferida");
    a.put(bxn.aD, "PayPal protege tu <a href='%s'>privacidad</a> y tu información financiera.");
    a.put(bxn.aE, "Proceso en curso");
    a.put(bxn.aF, "Recordar tarjeta");
    a.put(bxn.aG, "Solicitar dinero");
    a.put(bxn.aH, "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    a.put(bxn.aI, "De ahorro");
    a.put(bxn.aJ, "Enviar dinero");
    a.put(bxn.aK, "Se ha producido un problema de comunicación con los servidores de PayPal. Inténtalo de nuevo.");
    a.put(bxn.aL, "Vuelve a iniciar sesión en PayPal.");
    a.put(bxn.aM, "La sesión ha caducado");
    a.put(bxn.aN, "Dirección de envío");
    a.put(bxn.aO, "¿No tienes una cuenta PayPal? Registrarse");
    a.put(bxn.aP, "Mantener sesión abierta");
    a.put(bxn.aQ, "Error del sistema (%s). Inténtalo de nuevo más tarde.");
    a.put(bxn.aR, "Inténtalo de nuevo");
    a.put(bxn.aS, "No es posible iniciar sesión porque se ha activado la autenticación de dos factores para la cuenta.");
    a.put(bxn.aT, "Código de seguridad");
    a.put(bxn.aU, "Envía un mensaje de texto a tu teléfono. El código de 6 dígitos que recibas será válido durante 5 minutos.");
    a.put(bxn.aV, "Envío de mensaje de texto");
    a.put(bxn.aW, "Introduce el código de seguridad de 6 dígitos");
    a.put(bxn.aX, "Tu número de teléfono móvil");
    a.put(bxn.aY, "Enviar mensaje de texto");
    a.put(bxn.aZ, "Enviar mensaje de texto de nuevo");
    a.put(bxn.ba, "No es posible iniciar sesión porque se ha activado la autenticación de dos factores para la cuenta. Para activar tu clave de seguridad, visita el sitio web de PayPal.");
    a.put(bxn.bb, "No se admiten pagos desde este dispositivo.");
    a.put(bxn.bc, "Dispositivo no autorizado");
    a.put(bxn.bd, "No se permiten los pagos a este vendedor (Id. de cliente no válido).");
    a.put(bxn.be, "Vendedor no válido");
    a.put(bxn.bf, "Ha habido un problema al procesar el pago. Inténtalo de nuevo.");
    a.put(bxn.bg, "Fuente no identificada");
    a.put(bxn.bh, "Lo sentimos");
    a.put(bxn.bi, "Tu pedido");
    a.put(bxn.bj, "¿Borrar tarjeta?");
    a.put(bxn.bk, "Error en el consentimiento");
    a.put(bxn.bl, "Error de conexión");
    a.put(bxn.bm, "Error de inicio de sesión");
    a.put(bxn.bn, "Iniciar sesión con contraseña");
    a.put(bxn.bo, "Iniciar sesión con PIN");
    a.put(bxn.bp, "Un momento…");
    a.put(bxn.bq, "Error en el pago");
    a.put(bxn.br, "Escanear");
    a.put(bxn.bs, "Código de seguridad incorrecto. Inténtalo de nuevo.");
    a.put(bxn.bt, "Mediante");
    a.put(bxn.bu, "Error del sistema. Inténtalo de nuevo más tarde.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Compartir información sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Compartir la información sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Compartir información sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Compartir información sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Compartir información sobre las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Compartir información con ellos sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Compartir las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Compartir las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Compartir la información sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Compartir información sobre las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Compartir la información sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Compartir información sobre las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indica a PayPal que pague todos los importes solicitados por %3$s.</p><p>Consulta el <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Acuerdo de pagos periódicos y facturación de PayPal</a> para obtener más información.</p>");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indica a PayPal que pague todos los importes solicitados por %3$s.</p><p>Consulta el <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Acuerdo de pagos periódicos y facturación de PayPal</a> para obtener más información.</p>");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras pagadas con PayPal. Autoriza y solicita a PayPal que pague todos los importes.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras pagadas con PayPal. Autoriza y solicita a PayPal que pague todos los importes.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras pagadas con PayPal. Autoriza y solicita a PayPal que pague todos los importes.");
    b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preaprueba pagos futuros realizados desde tu cuenta PayPal sin iniciar sesión en PayPal cada vez. <a href='%1$s'>Consulta las condiciones adicionales</a>, incluidas las formas de pago y cómo se cancelan los pagos futuros.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte información sobre las fuentes de fondos disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte información sobre las fuentes de fondos disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte información sobre las fuentes de fondos disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que están disponibles para su uso.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se transferirá dinero.</p><p>Se utilizará la forma de pago predeterminada (el saldo de PayPal, cuenta bancaria, tarjeta de débito o una tarjeta de crédito vinculada, por este orden) para pagar las compras con PayPal. Ten en cuenta que si no hay fondos suficientes en la forma de pago predeterminada para cubrir la compra, el banco o la entidad emisora de la tarjeta pueden cargarte una comisión.</p><p>Para cancelar este acuerdo, inicia sesión en tu cuenta PayPal y ve a <strong>Perfil</strong>, a continuación haz clic en <strong>Opciones de cuenta</strong> y en el vínculo <strong>Cambiar</strong> situado junto a la opción “Iniciar sesión con PayPal”.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará el saldo de PayPal o la tarjeta de débito o crédito principal para pagar las compras con PayPal.</p><p>Para cancelar este acuerdo, inicia sesión en tu cuenta PayPal y ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar este acuerdo, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Se utilizará la fuente de fondos predeterminada para realizar futuros pagos con PayPal desde este vendedor.</p><p>Para cancelar este acuerdo, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Se aplicará la sección Pagos periódicos de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarte de que los pagos con tu cuenta PayPal funcionen correctamente, esta aplicación puede simular una pequeña transacción de prueba, pero no se transferirá dinero.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorización de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorización, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuración de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener más información, consulta la sección “Pagos con aprobación previa” de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorización de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorización, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuración de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener más información, consulta la sección “Pagos con aprobación previa” de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará el saldo de PayPal o la tarjeta de débito o crédito principal para pagar las compras con PayPal.</p><p>Para cancelar este acuerdo, inicia sesión en tu cuenta PayPal y ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autorización de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorización, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuración de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener más información, consulta la sección “Pagos con aprobación previa” de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autorización de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorización, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuración de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener más información, consulta la sección “Pagos con aprobación previa” de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorización de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicación puede simular una pequeña transacción de prueba, pero no se realizará ningún pago.</p><p>Se utilizará la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorización, inicia sesión en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuración de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener más información, consulta la sección “Pagos con aprobación previa” de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
    b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>PayPal usará primero el saldo de la cuenta PayPal para pagar las compras. Si este no cubre el total de la compra, para realizar el pago se utilizarán tu cuenta bancaria, PayPal Credit, la tarjeta de débito, de crédito o el cargo en cuenta bancaria, en este orden.</p><p>Para cancelar este acuerdo, ve a www.paypal.com <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Es posible que tengas que autorizar un pequeño pago para asegurarte de que se pueden realizar cargos en tu cuenta PayPal en el futuro. La autorización se anulará y no se realizará cargo alguno.</p>");
    b.put("LOG_IN_TO_PAYPAL|AU", "Iniciar sesión con PayPal");
    b.put("LOG_IN_TO_PAYPAL|GB", "Iniciar sesión con PayPal");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el partner.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal y haz clic en el icono de la rueda dentada. Ve a <strong>Seguridad</strong>, selecciona <strong>Iniciar sesión con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, ve a opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el partner.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal y haz clic en el icono de la rueda dentada. Ve a <strong>Seguridad</strong>, selecciona <strong>Iniciar sesión con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el partner.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal y haz clic en el icono de la rueda dentada. Ve a <strong>Seguridad</strong>, selecciona <strong>Iniciar sesión con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, ve a las opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, haz clic en el icono de rueda dentada en la esquina superior derecha, selecciona <strong>Centro de seguridad</strong>, selecciona <strong>Iniciar sesión con PayPal</strong> y elimina al vendedor. Si aún utilizas el sitio web clásico, ve a <strong>Mi perfil</strong>, selecciona <strong>Configuración de cuenta</strong>, selecciona <strong>Iniciar sesión con PayPal</strong> y elimina al vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el partner.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal y, a continuación, en la configuración de <strong>Perfil</strong>, ve a <strong>Iniciar sesión con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.it, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, ve a opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, ve a las opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, ve a opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el partner.</p><p>Para retirar el consentimiento, inicia sesión en paypal.ru, haz clic en el icono de la rueda dentada en la esquina superior derecha, selecciona la pestaña <strong>Seguridad</strong> y elimina a este partner en la opción <strong>Iniciar sesión con PayPal</strong>.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en tu cuenta PayPal, ve a las opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com.tr, haz clic en el icono de rueda dentada de la esquina superior derecha, selecciona la pestaña <strong>Seguridad</strong> y elimina a este partner en la opción <strong>Iniciar sesión con PayPal</strong>.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a opciones de <strong>Iniciar sesión con PayPal</strong> en la configuración del <strong>Perfil</strong> y elimina a este vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacción se compartirán con el vendedor.</p><p>Para retirar el consentimiento, inicia sesión en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesión con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
    c.put("AMOUNT_MISMATCH", "El importe total de los artículos del carro de la compra no coincide con el importe de la venta.");
    c.put("AUTHORIZATION_ALREADY_COMPLETED", "Esta autorización ya se ha completado.");
    c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "El estado de la autorización no se puede anular.");
    c.put("AUTHORIZATION_EXPIRED", "La autorización ha caducado.");
    c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "El Id. de autorización solicitado no existe.");
    c.put("AUTHORIZATION_VOIDED", "La autorización se ha anulado.");
    c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Solo puedes volver a validar la autorización original, no una nueva autorización.");
    c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "No se permite realizar una nueva autorización durante el período de tramitación.");
    c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "El importe supera el límite permitido.");
    c.put("CARD_TOKEN_PAYER_MISMATCH", "No es posible acceder a la información de la tarjeta guardada.");
    c.put("CREDIT_CARD_CVV_CHECK_FAILED", "La información de la tarjeta no es válida. Corrígela y vuelve a enviarla.");
    c.put("CREDIT_CARD_REFUSED", "Tarjeta rechazada.");
    c.put("CURRENCY_MISMATCH", "La divisa de la captura debe ser igual que la divisa de la autorización.");
    c.put("CURRENCY_NOT_ALLOWED", "Actualmente, PayPal no admite esta divisa.");
    c.put("DATA_RETRIEVAL", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("DUPLICATE_REQUEST_ID", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("EXPIRED_CREDIT_CARD", "La tarjeta ha caducado");
    c.put("EXPIRED_CREDIT_CARD_TOKEN", "La información de esta tarjeta ya no figura en nuestros registros.\nVuelve a enviarla.");
    c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Función no admitida para este proveedor.");
    c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Parte del importe de esta transacción ya se ha reembolsado.");
    c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Pago inmediato no compatible con la finalidad pasada.");
    c.put("INSTRUMENT_DECLINED", "No se ha aceptado la forma de pago seleccionada. Elige otra forma de pago.");
    c.put("INSUFFICIENT_FUNDS", "El comprador no puede pagar: saldo insuficiente.");
    c.put("INTERNAL_SERVICE_ERROR", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("INVALID_ACCOUNT_NUMBER", "Ese número de cuenta no existe.");
    c.put("INVALID_ARGUMENT", "Transacción rechazada debido a un argumento no válido");
    c.put("INVALID_CITY_STATE_ZIP", "Combinación de ciudad/estado/código postal no válida.");
    c.put("INVALID_FACILITATOR_CONFIGURATION", "Esta transacción no se puede procesar debido a una configuración del facilitador no válida.");
    c.put("INVALID_PAYER_ID", "Error del sistema (Id. de pagador no válido). Inténtalo de nuevo más tarde.");
    c.put("INVALID_RESOURCE_ID", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("PAYEE_ACCOUNT_INVALID", "El correo electrónico de la cuenta del proveedor no está confirmado.");
    c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Este proveedor no puede recibir pagos en este momento.");
    c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "El correo electrónico de la cuenta del proveedor no está confirmado.");
    c.put("PAYEE_ACCOUNT_RESTRICTED", "Este proveedor no puede recibir pagos en este momento.");
    c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "La cuenta está bloqueada o cerrada.");
    c.put("PAYER_ACCOUNT_RESTRICTED", "Tu cuenta está restringida.");
    c.put("PAYER_CANNOT_PAY", "No puedes ingresar fondos para esta transacción con PayPal.");
    c.put("PAYER_EMPTY_BILLING_ADDRESS", "La dirección de facturación es obligatoria para transacciones con tarjetas de crédito que no sean de PayPal.");
    c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "No es posible acceder a la información de la tarjeta guardada.");
    c.put("PAYMENT_APPROVAL_EXPIRED", "La aprobación del pago ha caducado.");
    c.put("PAYMENT_EXPIRED", "El pago ha caducado.");
    c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "El pagador no ha aprobado el pago.");
    c.put("PAYMENT_REQUEST_ID_INVALID", "El Id. de la solicitud de PayPal no es válido. Inténtalo de nuevo más tarde.");
    c.put("PAYMENT_STATE_INVALID", "Esta solicitud no es válida debido al estado actual del pago.");
    c.put("PERMISSION_DENIED", "No se permite la operación solicitada.");
    c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "El reembolso solicitado supera el importe de la transacción original.");
    c.put("REFUND_TIME_LIMIT_EXCEEDED", "Esta transacción se considera demasiado antigua para ser objeto de reembolso.");
    c.put("REQUIRED_SCOPE_MISSING", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("TOO_MANY_REAUTHORIZATIONS", "No se permiten más autorizaciones nuevas para esta autorización.");
    c.put("TRANSACTION_ALREADY_REFUNDED", "El importe de esta transacción ya se ha reembolsado.");
    c.put("TRANSACTION_LIMIT_EXCEEDED", "El importe supera el límite permitido.");
    c.put("TRANSACTION_REFUSED", "Esta transacción se ha rechazado.");
    c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Esta transacción se ha rechazado.");
    c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "La preferencia del perfil del vendedor está configurada para rechazar automáticamente ciertas transacciones.");
    c.put("UNKNOWN_ERROR", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("UNSUPPORTED_PAYEE_COUNTRY", "País no admitido.");
    c.put("VALIDATION_ERROR", "La información de pago no es válida. Corrígela y vuelve a enviarla.");
    c.put("ORDER_ALREADY_COMPLETED", "El pedido ya se ha anulado, ha caducado o se ha completado.");
    c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Se ha alcanzado el número máximo de autorizaciones permitidas para el pedido.");
    c.put("ORDER_VOIDED", "Se ha anulado el pedido.");
    c.put("ORDER_CANNOT_BE_VOIDED", "El estado del pedido hace que no sea posible su cancelación.");
    c.put("INVALID_EXPERIENCE_PROFILE_ID", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("UNAUTHORIZED_PAYMENT", "El vendedor no acepta pagos de este tipo.");
    c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Divisa no admitida para el tipo de tarjeta.");
    c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo de tarjeta no admitido.");
    c.put("ADDRESS_ADDITION_ERROR", "Error detectado al añadir la dirección de envío a la cuenta PayPal.");
    c.put("DUPLICATE_TRANSACTION", "Transacción duplicada.");
    c.put("INVALID_SHIPPING_ADDRESS", "La dirección de envío proporcionada no es válida.");
    c.put("PAYMENT_CREATION_ERROR", "Ha surgido un problema al configurar el pago. Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Ha surgido un problema al configurar el pago: la tarjeta ha caducado. Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Ha surgido un problema al configurar el pago: se requiere un método de pago instantáneo (por ejemplo, una tarjeta de crédito). Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Ha surgido un problema al configurar el pago: se debe confirmar la tarjeta. Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Ha surgido un problema al configurar el pago: la aplicación requiere que la cuenta incluya un número de teléfono. Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Ha surgido un problema al configurar el pago: la cuenta precisa una fuente de fondos válida (por ejemplo, un banco o una tarjeta de pago). Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Ha surgido un problema al configurar el pago: el saldo es negativo. Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Ha surgido un problema al configurar el pago: se ha alcanzado el límite de envío. Visita el sitio web de PayPal para consultar la cuenta.");
    c.put("AUTH_RC_RISK_FAILURE", "Rechazada debido al riesgo.");
    c.put("AUTH_RC_OFAC_BLOCKED_IP", "Cliente no autorizado.");
    c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Cliente no autorizado.");
    c.put("invalid_user", "Nombre de usuario o contraseña incorrectos. Inténtalo de nuevo.");
    c.put("locked_user", "Tu cuenta PayPal está bloqueada temporalmente. Inténtalo de nuevo más tarde o ve a www.paypal.com para desbloquear tu cuenta PayPal de inmediato.");
    c.put("max_attempts_exceeded", "Demasiados intentos fallidos de inicio de sesión. Inténtalo de nuevo más tarde.");
    c.put("invalid_request", "Ha habido un error.");
    c.put("unauthorized_client", "Solicitud no autorizada.");
    c.put("access_denied", "Solicitud no autorizada.");
    c.put("unsupported_response_type", "Ha habido un error.");
    c.put("invalid_scope", "Solicitud no autorizada.");
    c.put("server_error", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("temporarily_unavailable", "Error del sistema. Inténtalo de nuevo más tarde.");
    c.put("stepup_required", "El inicio de sesión no se puede completar en este momento. Inténtalo de nuevo más tarde o ve a www.paypal.com para tratar cualquier problema de seguridad con tu cuenta PayPal.");
  }
  
  public final String a()
  {
    return "es";
  }
  
  public final String a(String paramString)
  {
    return (String)c.get(paramString);
  }
}

/* Location:
 * Qualified Name:     cfy
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */